from typing import Dict, List, Tuple

KEYMAP: Dict[str, str] = {
    "Esc": "KEY_ESC",
    "F1": "KEY_F1",
    "F2": "KEY_F2",
    "F3": "KEY_F3",
    "F4": "KEY_F4",
    "F5": "KEY_F5",
    "F6": "KEY_F6",
    "F7": "KEY_F7",
    "F8": "KEY_F8",
    "F9": "KEY_F9",
    "F10": "KEY_F10",
    "F11": "KEY_F11",
    "F12": "KEY_F12",
    "PrtSc": "KEY_SYSRQ",
    "ScrLk": "KEY_SCROLLLOCK",
    "Pause": "KEY_PAUSE",
    "`": "KEY_GRAVE",
    "1": "KEY_1",
    "2": "KEY_2",
    "3": "KEY_3",
    "4": "KEY_4",
    "5": "KEY_5",
    "6": "KEY_6",
    "7": "KEY_7",
    "8": "KEY_8",
    "9": "KEY_9",
    "0": "KEY_0",
    "-": "KEY_MINUS",
    "=": "KEY_EQUAL",
    "Backspace": "KEY_BACKSPACE",
    "Ins": "KEY_INSERT",
    "Home": "KEY_HOME",
    "PgUp": "KEY_PAGEUP",
    "Tab": "KEY_TAB",
    "Q": "KEY_Q",
    "W": "KEY_W",
    "E": "KEY_E",
    "R": "KEY_R",
    "T": "KEY_T",
    "Y": "KEY_Y",
    "U": "KEY_U",
    "I": "KEY_I",
    "O": "KEY_O",
    "P": "KEY_P",
    "[": "KEY_LEFTBRACE",
    "]": "KEY_RIGHTBRACE",
    "\\": "KEY_BACKSLASH",
    "Del": "KEY_DELETE",
    "End": "KEY_END",
    "PgDn": "KEY_PAGEDOWN",
    "Caps": "KEY_CAPSLOCK",
    "A": "KEY_A",
    "S": "KEY_S",
    "D": "KEY_D",
    "F": "KEY_F",
    "G": "KEY_G",
    "H": "KEY_H",
    "J": "KEY_J",
    "K": "KEY_K",
    "L": "KEY_L",
    ";": "KEY_SEMICOLON",
    "'": "KEY_APOSTROPHE",
    "Enter": "KEY_ENTER",
    "Shift": "KEY_LEFTSHIFT",
    "Z": "KEY_Z",
    "X": "KEY_X",
    "C": "KEY_C",
    "V": "KEY_V",
    "B": "KEY_B",
    "N": "KEY_N",
    "M": "KEY_M",
    ",": "KEY_COMMA",
    ".": "KEY_DOT",
    "/": "KEY_SLASH",
    "RShift": "KEY_RIGHTSHIFT",
    "Up": "KEY_UP",
    "Ctrl": "KEY_LEFTCTRL",
    "Win": "KEY_LEFTMETA",
    "Alt": "KEY_LEFTALT",
    "Space": "KEY_SPACE",
    "AltGr": "KEY_RIGHTALT",
    "Menu": "KEY_MENU",
    "Ctrl2": "KEY_RIGHTCTRL",
    "Left": "KEY_LEFT",
    "Down": "KEY_DOWN",
    "Right": "KEY_RIGHT",
    "NumLk": "KEY_NUMLOCK",
    "Num/": "KEY_KPSLASH",
    "Num*": "KEY_KPASTERISK",
    "Num-": "KEY_KPMINUS",
    "Num7": "KEY_KP7",
    "Num8": "KEY_KP8",
    "Num9": "KEY_KP9",
    "Num+": "KEY_KPPLUS",
    "Num4": "KEY_KP4",
    "Num5": "KEY_KP5",
    "Num6": "KEY_KP6",
    "Num1": "KEY_KP1",
    "Num2": "KEY_KP2",
    "Num3": "KEY_KP3",
    "NumEnter": "KEY_KPENTER",
    "Num0": "KEY_KP0",
    "Num.": "KEY_KPDOT",
    "M1": "KEY_MACRO1",
    "M2": "KEY_MACRO2",
    "M3": "KEY_MACRO3",
    "M4": "KEY_MACRO4",
    "M5": "KEY_MACRO5",
}

MOUSEMAP: Dict[str, str] = {
    "LMB": "BTN_LEFT",
    "RMB": "BTN_RIGHT",
    "MMB": "BTN_MIDDLE",
    "M4": "BTN_SIDE",
    "M5": "BTN_EXTRA",
}

KEY_ALIASES: Dict[str, List[str]] = {
    "M1": ["KEY_MACRO1", "KEY_PROG1", "KEY_F13", "656", "183"],
    "M2": ["KEY_MACRO2", "KEY_PROG2", "KEY_F14", "657", "184"],
    "M3": ["KEY_MACRO3", "KEY_PROG3", "KEY_F15", "658"],
    "M4": ["KEY_MACRO4", "KEY_PROG4", "KEY_F16", "659"],
    "M5": ["KEY_MACRO5", "KEY_PROG5", "KEY_F17", "660"],
}

MOUSE_ALIASES: Dict[str, List[str]] = {
    "M4": ["BTN_SIDE", "BTN_BACK", "278"],
    "M5": ["BTN_EXTRA", "BTN_FORWARD", "277"],
}

KEYBOARD_LAYOUT: List[List[Tuple[str, int]]] = [
    [
        ("M1", 1),
        ("Esc", 1),
        ("F1", 1),
        ("F2", 1),
        ("F3", 1),
        ("F4", 1),
        ("F5", 1),
        ("F6", 1),
        ("F7", 1),
        ("F8", 1),
        ("F9", 1),
        ("F10", 1),
        ("F11", 1),
        ("F12", 1),
        ("PrtSc", 1),
        ("ScrLk", 1),
        ("Pause", 1),
    ],
    [
        ("M2", 1),
        ("`", 1),
        ("1", 1),
        ("2", 1),
        ("3", 1),
        ("4", 1),
        ("5", 1),
        ("6", 1),
        ("7", 1),
        ("8", 1),
        ("9", 1),
        ("0", 1),
        ("-", 1),
        ("=", 1),
        ("Backspace", 2),
        ("Ins", 1),
        ("Home", 1),
        ("PgUp", 1),
        ("NumLk", 1),
        ("Num/", 1),
        ("Num*", 1),
        ("Num-", 1),
    ],
    [
        ("M3", 1),
        ("Tab", 2),
        ("Q", 1),
        ("W", 1),
        ("E", 1),
        ("R", 1),
        ("T", 1),
        ("Y", 1),
        ("U", 1),
        ("I", 1),
        ("O", 1),
        ("P", 1),
        ("[", 1),
        ("]", 1),
        ("\\", 1),
        ("Del", 1),
        ("End", 1),
        ("PgDn", 1),
        ("Num7", 1),
        ("Num8", 1),
        ("Num9", 1),
        ("Num+", 1),
    ],
    [
        ("M4", 1),
        ("Caps", 2),
        ("A", 1),
        ("S", 1),
        ("D", 1),
        ("F", 1),
        ("G", 1),
        ("H", 1),
        ("J", 1),
        ("K", 1),
        ("L", 1),
        (";", 1),
        ("'", 1),
        ("Enter", 2),
        ("Num4", 1),
        ("Num5", 1),
        ("Num6", 1),
        ("Num+", 1),
    ],
    [
        ("M5", 1),
        ("Shift", 2),
        ("Z", 1),
        ("X", 1),
        ("C", 1),
        ("V", 1),
        ("B", 1),
        ("N", 1),
        ("M", 1),
        (",", 1),
        (".", 1),
        ("/", 1),
        ("RShift", 2),
        ("Up", 1),
        ("Num1", 1),
        ("Num2", 1),
        ("Num3", 1),
        ("NumEnter", 1),
    ],
    [
        ("Ctrl", 1),
        ("Win", 1),
        ("Alt", 1),
        ("Space", 6),
        ("AltGr", 1),
        ("Menu", 1),
        ("Ctrl2", 1),
        ("Left", 1),
        ("Down", 1),
        ("Right", 1),
        ("Num0", 2),
        ("Num.", 1),
    ],
]

MX_CAPTURE_SEQUENCE = ["M5", "M4", "M3", "M2", "M1"]
FULL_KEY_CAPTURE_SEQUENCE = list(
    dict.fromkeys(key for row in KEYBOARD_LAYOUT for key, _ in row if key in KEYMAP)
)
TOP_TAB_ORDER = ["TECLADO", "MOUSE", "MACROS"]
SUB_TAB_ORDER = ["PERSONALIZAR", "DESEMPENHO", "ILUMINACAO"]
